package:
  name: postgres-xl
  version: 9.5

source:
  fn: postgres-xl-9.5r1beta2.tar.gz
  url: http://files.postgres-xl.org/postgres-xl-9.5r1beta2.tar.gz
  patches:
    - prefer_ncurses_to_termcap.patch

build:
  number: 1

requirements:
  build:
    - gcc
    - flex
    - python
    - openssl
    - ncurses
    - readline
    - libxml2
    - libxslt
    - zlib
  run:
    - libgcc
    - python
    - openssl
    - ncurses
    - readline
    - libxml2
    - libxslt
    - zlib

test:
  commands:
    - postgres --help
    - initdb --help
    - createdb --help
    - psql --help
    - initgtm --help
    - gtm --help
    - pgxc_ctl --help

about:
  home: http://www.postgres-xl.org
  license: MIT

# vim:set ts=8 sw=2 sts=2 tw=78 et:
